version: '3.8'

services:
  postgres:
    image: ankane/pgvector:latest  # Image PostgreSQL với pgvector đã được cài sẵn
    container_name: pgvector_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: vector_db
    ports:
      - "5432:5432"
    volumes:
      - pgvector_data:/var/lib/postgresql/data

volumes:
  pgvector_data:
